language: php

php:
    - 7.1
#    - 7.2
#    - nightly

install:
    - composer install
    - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
    - chmod +x ./cc-test-reporter

before_script:
  - ./cc-test-reporter before-build

script:
    - composer test-ci

after_script:
    - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
