env:
    global:
        - CC_TEST_REPORTER_ID=3ddb24a78e7cd3362b97058bafc441cb167caa51781cbf7cb5b3a62b145b56ff

language: php

php:
    - 7.1
    - 7.2

install:
    - composer install
    - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
    - chmod +x ./cc-test-reporter

before_script:
  - ./cc-test-reporter before-build

script:
    - composer test-ci

after_script:
    - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT

